# Generated by Django 5.0.7 on 2024-07-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('Junior', 'Junior'), ('Middle ', 'Middle'), ('Senior', 'Senior')], default='Junior', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers/')),
            ],
        ),
    ]
